In [19]:
import pandas as pd
import csv
import numpy as np

In [4]:
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))

In [5]:
df.head()

    A   B   C   D
0  93   8  47  39
1  89  71  72  12
2  99  41  39  64
3  35  88  38  61
4  12   1  33  75

In [32]:
for it in df.index:
    for col in df.columns:
        print(df[col][it])

93
8
47
39
89
71
72
12
99
41
39
64
35
88
38
61
12
1
33
75
42
4
19
27
94
28
54
35
12
67
11
63
2
2
81
54
54
50
67
80
26
69
28
73
94
49
10
53
60
31
98
75
54
23
74
6
79
6
57
29
87
44
33
18
16
34
28
19
96
38
76
85
63
69
25
91
23
56
98
5
33
65
76
69
64
59
56
85
61
47
12
52
89
17
17
27
27
10
11
19
81
50
55
72
89
0
84
34
42
71
5
7
71
27
64
65
86
4
37
61
1
96
15
39
39
34
75
6
63
29
83
55
82
73
36
4
16
89
88
77
45
35
80
13
11
56
86
98
17
78
1
88
6
82
58
52
10
18
55
40
85
39
34
7
42
62
2
6
12
65
14
47
10
56
60
98
58
18
17
25
23
98
29
62
79
67
46
93
66
27
98
64
29
9
23
99
2
93
68
42
86
86
41
66
67
97
91
25
16
77
33
52
45
78
24
74
50
25
67
29
35
83
7
6
53
71
32
44
12
67
83
83
54
97
4
36
59
35
35
61
10
47
46
0
93
87
52
73
5
50
80
79
68
78
29
3
1
99
57
71
14
92
39
57
79
14
76
7
45
3
50
31
91
41
3
11
63
95
1
0
1
31
37
86
99
10
19
97
12
11
74
94
63
69
33
71
48
76
99
56
62
68
52
20
19
66
64
84
54
35
1
97
13
50
3
62
3
2
35
76
0
7
86
32
91
49
94
7
90
50
30
53
49
50
11
56
84
75
90
60
17
65
14
17
50
1
6
52
39
20
41
26
78
21
15
45
68
56
81
63
16
73
47
68
68
84
26
99
47
78
7
68
69
18
18
98
31
48
76
80
50
48
5
64
27
62
46
56
29
97
24
24
15
63
24
33
94
30
61
26

In [36]:
for i in df.columns:
    print(df[col])

0     39
1     12
2     64
3     61
4     75
      ..
95    64
96    56
97    24
98    33
99    26
Name: D, Length: 100, dtype: int64
0     39
1     12
2     64
3     61
4     75
      ..
95    64
96    56
97    24
98    33
99    26
Name: D, Length: 100, dtype: int64
0     39
1     12
2     64
3     61
4     75
      ..
95    64
96    56
97    24
98    33
99    26
Name: D, Length: 100, dtype: int64
0     39
1     12
2     64
3     61
4     75
      ..
95    64
96    56
97    24
98    33
99    26
Name: D, Length: 100, dtype: int64